# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "milestone-2" branch
  push:
    branches: [ "milestone-2" ]
  pull_request:
    branches: [ "milestone-2" ]

# to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://mmr44:$HF_TOKEN@huggingface.co/spaces/mmr44/CS670-Project main
